# all the default rules are enabled, except for explicitly disabled ones. Check default rules here: https://realm.github.io/SwiftLint/rule-directory.html
# rules may be disabled with swiftlint:disable:next/this/previous rule_name
disabled_rules:
- trailing_whitespace

opt_in_rules:
- array_init
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- convenience_type
- discarded_notification_center_observer
- discouraged_none_name
- discouraged_object_literal
- discouraged_optional_boolean
- empty_count
- empty_string
- empty_collection_literal
- explicit_init
- fatal_error_message
- file_name
- file_name_no_space
- file_types_order
- first_where
# please note that sometimes force unwrapping is ok, one should be able to explain its usage in the comments
- force_unwrapping
- last_where
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- operator_usage_whitespace
- overridden_super_call
- prefer_zero_over_explicit_init
- prohibited_interface_builder
- prohibited_super_call
- redundant_type_annotation
- shorthand_optional_binding
- sorted_first_last
- sorted_imports
- toggle_bool
- type_contents_order
- vertical_whitespace_between_cases
- weak_delegate
- yoda_condition
- unused_import

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"

identifier_name:
    allowed_symbols: ["_"]
    min_length: 3
    max_length: 40
    validates_start_with_lowercase: false
    
custom_rules:
  final_class:
    regex: '^(?!\s*final\b)\s*(public|internal|private|fileprivate)?\s*class\s'
    message: "Final Classes Requirement Violation: all classes should be marked as final. Silence this warning if your class should be inherited"
